---
title: "TzeFungLung_Assign8"
author: "jim lung"
date: "10-20-2017"
output: html_document
---

# Data 605 Assignment 8

## Page 303 # 11
## 11 A company buys 100 lightbulbs, each of which has an exponential lifetime of 1000 hours. What is the expected time for the first of these bulbs to burn out? (See Exercise 10.)
Expected value:

\[E[X_i]=\frac{1}{\lambda_i}\]

\[\lambda=\lambda_1+...+\lambda_{100}=\frac{100}{1000}=\frac{1}{10}\]

\[E[X_i]=\frac{1}{0.1}\]

Expected value is 10 hours.

## Page 303 # 14
## 14 Assume that X1 and X2 are independent random variables, each having an exponential density with parameter £f. Show that Z = X1 ??? X2 has density
\[fZ(z) = (1/2)\lambda e^{-\lambda\mid z\mid }\]


\[X_1 = Z + X_2\]
When $X_2 \geq X_1$, $-\infty \; to \; 0$

\[f_Z(z) = \int_{-\infty}^{\infty}f_{X_1}(x_1)f_{X_2}(x_2)dx_2\]
\[f_Z(z) = \int_{-\infty}^{\infty}f_{X_1}(z+x_2)f_{X_2}(x_2)dx_2\]
\[f_{X_1}(z+x_2) = \lambda e^{-\lambda (z+x_2)}\]
\[f_{X_2}(x_2)= \lambda e^{-2\lambda x_2}\]
\[f_Z(z) = \int_{-\infty}^0\lambda e^{-\lambda (z+x_2)} \lambda e^{-\lambda x_2}dx_2\]
\[f_Z(z) = \lambda^2 e^{-\lambda z}(\frac{ -1}{2\lambda})\]
\[f_Z(z) = \frac{-\lambda e^{-\lambda z}}{2}\]


when $X_1 \geq X_2$, $0 \; to \; \infty$
\[f_Z(z) = \int_0^{\infty}\lambda e^{-\lambda (z+x_2)} \lambda e^{-\lambda x_2}dx_2\]
\[f_Z(z) = \lambda^2 e^{-\lambda z}(\frac{ -1}{2\lambda})\]
\[f_Z(z) = \frac{\lambda e^{-\lambda z}}{2}\]

## Page 320 # 1

## 1 Let X be a continuous random variable with mean £g = 10 and variance £m^2 = 100/3. Using Chebyshev¡¦s Inequality, find an upper bound for the following probabilities.

$$mean £g = 10$$
$$variance £m^2 = 100/3$$
$$Standard deviation £m = sqrt (100/3)$$


\[P(|X-\mu|\geq k\sigma)\leq\frac{1}{k^2}\]


### (a) P( | X - 10 | >= 2)

\[ k \sigma=2 \]
\[  k= \frac{2}{\sqrt{100/3}} \]
\[ P(|X - 10|\geqslant 2) = \frac{1}{k^{_{2}}} = 8.3333 \approx 1\] 


### (b) P( | X - 10 | >= 5)
\[ k \sigma=5 \]
\[ k= \frac{5}{\sqrt{100/3}} \]
\[ P(|X - 10|\geqslant 5) = \frac{1}{k^{_{2}}} = 1.3333 \approx 1$ \]

### (c) P( | X - 10 | >= 9)
\[ k \sigma=9 \]
\[ k= \frac{9}{\sqrt{100/3}} \]
\[ P(|X - 10|\geqslant 9) = \frac{1}{k^{_{2}}} = 0.4115 \]

### (d) P( | X - 10 | >= 20)
\[ k \sigma=20 \]
\[ k= \frac{20}{\sqrt{100/3}} \]
\[ P(|X - 10|\geqslant 20) = \frac{1}{k^{_{2}}} = 0.0833$ \]


Test:
```{r}
u <- 10
o <- sqrt(100/3)

x1 <-c(2, 5, 9, 20)

k <- (x1 )/o

p1 <-  round(1/(k^2), 4)
p1

```

