---
title: "discussionwk11"
author: "jim lung"
date: "11-09-2017"
output: html_document
---

# DATA 605 Discussion week 11

Using R, build a regression model for data that interests you. Conduct residual analysis. Was the linear model appropriate? Why or why not?

# Iris Data

```{r}
head(iris)
```


```{r}
summary(iris)
```


```{r}
library(ggplot2)
ggplot(data = iris, aes(x=Sepal.Length, y=Sepal.Width)) + geom_point(size = 2, alpha = .4) + geom_smooth(method = "lm", se = FALSE)
  
  
```

```{r}
#correlation:
cor(iris$Sepal.Length,iris$Sepal.Width)
```

```{r}
# linear model
Linear =lm(Sepal.Length~ Sepal.Width, data = iris)

summary(Linear)
```


```{r}
# scatterplot with least squares line
plot(iris$Sepal.Length~iris$Sepal.Width)
abline(Linear)
```

```{r}
# residuals plot with constant variability
plot(Linear$residuals ~ iris$Sepal.Length)
abline(h = 0, lty = 3)
```

```{r}
# histogram of residuals
hist(Linear$residuals)


```

```{r}
# qqplot
qqnorm(Linear$residuals)
qqline(Linear$residuals)
```

# histogram of residual plot appear to be normally distributed